### ISSUE TITLE
Minor nitpicking issues with the handbook

### ISSUE THREAD

**Issue by DanielYang59** [Quantum-Accelerators/handbook#1]
Hi Dr. Andrew and the Quacc team :),

Thanks a lot for the wonderful handbook, and I was just being curious so was looking through the handbook. It appears I cannot open a PR to directly modify the source code, so here I list a few nit picking issues I notice along the reading:
- [x] About the group - Overview: don't know whether it's possible at all or in which language it's written, but I guess dz^2 could be formatted as d<sub>z<sup>2</sup></sub>?
    > the mascot for our group is named Quacc and is a hybrid between a duck and a dz^2 orbital!
- [x] Group Logistics - Expectations - Working Hours and Work-Life Balance: An extra space after `while you're` (while you now know how curious I am about the work-life balance in Princeton):
   > This is mainly so I can reassign any time-sensitive tasks while you're  and so that I'm not bothering you while you travel. Note that sick days are entirely separate from vacation days!

**Comment by Andrew-S-Rosen** [comment]
@DanielYang59: Thanks for the comments! 

I'm using www.slite.com, so there's no source code :) sadly, no support for in-line LaTeX, but I fixed the grammar issue you pointed out. 

Thanks for stopping by virtually!

**Comment by DanielYang59** [comment]
Thanks a lot for the comment and fixing that! 

All the best.
